"""
工具模块
"""

from app.utils.exceptions import (
    FitnessAgentError,
    LLMError,
    LLMConnectionError,
    LLMTimeoutError,
    LLMRateLimitError,
    LLMAuthenticationError,
    LLMContentFilterError,
    ToolError,
    ToolNotFoundError,
    ToolValidationError,
    ToolExecutionError,
    MCPError,
    MCPConnectionError,
    MCPTimeoutError,
    RAGError,
    RAGIndexError,
    RAGRetrievalError,
    AuthenticationError,
    InvalidTokenError,
    TokenExpiredError,
    ValidationError,
    ResourceNotFoundError,
    RateLimitExceededError,
)
from app.utils.logger import (
    get_logger,
    setup_logging,
    LogContext,
    bind_context,
    unbind_context,
    clear_context,
)
from app.utils.rate_limiter import (
    InMemoryRateLimiter,
    RateLimitMiddleware,
    get_rate_limiter,
)
from app.utils.metrics import (
    record_chat_request,
    record_llm_call,
    record_tool_call,
    record_rag_hit,
    record_error,
    record_redis_operation,
    record_db_operation,
    set_app_info,
    set_active_sessions,
    CHAT_REQUESTS_TOTAL,
    CHAT_LATENCY_SECONDS,
    LLM_LATENCY_SECONDS,
    LLM_TOKENS_TOTAL,
    TOOL_CALLS_TOTAL,
    RAG_HITS_TOTAL,
)
from app.utils.cache import (
    LLMResponseCache,
    get_llm_cache,
)

__all__ = [
    # Exceptions
    "FitnessAgentError",
    "LLMError",
    "LLMConnectionError",
    "LLMTimeoutError",
    "LLMRateLimitError",
    "LLMAuthenticationError",
    "LLMContentFilterError",
    "ToolError",
    "ToolNotFoundError",
    "ToolValidationError",
    "ToolExecutionError",
    "MCPError",
    "MCPConnectionError",
    "MCPTimeoutError",
    "RAGError",
    "RAGIndexError",
    "RAGRetrievalError",
    "AuthenticationError",
    "InvalidTokenError",
    "TokenExpiredError",
    "ValidationError",
    "ResourceNotFoundError",
    "RateLimitExceededError",
    # Logger
    "get_logger",
    "setup_logging",
    "LogContext",
    "bind_context",
    "unbind_context",
    "clear_context",
    # Rate Limiter
    "InMemoryRateLimiter",
    "RateLimitMiddleware",
    "get_rate_limiter",
    # Metrics
    "record_chat_request",
    "record_llm_call",
    "record_tool_call",
    "record_rag_hit",
    "record_error",
    "record_redis_operation",
    "record_db_operation",
    "set_app_info",
    "set_active_sessions",
    "CHAT_REQUESTS_TOTAL",
    "CHAT_LATENCY_SECONDS",
    "LLM_LATENCY_SECONDS",
    "LLM_TOKENS_TOTAL",
    "TOOL_CALLS_TOTAL",
    "RAG_HITS_TOTAL",
    # Cache
    "LLMResponseCache",
    "get_llm_cache",
]
